name: Dart package analyze

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  analyze:
    name: Check pub score
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Analyze package
        uses: axel-op/dart-package-analyzer@v3
        id: workflow
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
