name: Flutter test

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  test:
    name: Flutter test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install Flutter
        uses: subosito/flutter-action@v2
      - name: Flutter pub get
        run: flutter pub get
      - name: Flutter test
        run: flutter test
